/// Flutter icons NotiIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NotiIcons
///      fonts:
///       - asset: fonts/NotiIcons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///
import 'package:flutter/widgets.dart';

class NotiIcons {
  NotiIcons._();

  static const _kFontFam = 'NotiIcons';

  static const IconData compass_1 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData compass_2 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData compass = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe803, fontFamily: _kFontFam);
}
